### ISSUE TITLE
New LICENCE: only students, teachers, professors 

### ISSUE THREAD

**Issue by samuel-cavalcanti** [CoppeliaRobotics/zmqRemoteApi#14]
Hi, if I understand correctly, you've changed the licence in such way that a hobbyist like me can't legally use your product, right ?

I'm not a student anymore, so I don't have an education email and my work has nothing to do with robots. I just do some experiments for fun

**Comment by Coppelia** [comment]
Hi Samuel, we had to slightly modify the wording, since we constantly see an increase in CoppeliaSim Edu usage, while catching many companies red-handed using the Edu version in a non-Edu and commercial setting. 
You and other hobbyists can of course still get to use CoppeliaSim Edu, we are happy to generate an Edu key if you send us the displayed mid3-value in the terminal.

**Comment by samuel-cavalcanti** [comment]
What is a mid3-value  ?

**Comment by Coppelia** [comment]
Start CoppeliaSim V4.8 (or later) and you'll see it in the terminal/console

**Comment by samuel-cavalcanti** [comment]
```sh
[CoppeliaSim:loadinfo]   midx: 5000-D5FB-FFC4-9C88-F7EB-D91D
[CoppeliaSim:loadinfo]   did:
[CoppeliaSim:loadinfo]   mid0: 3094-3B4B-BA16-0000-2578-0101
[CoppeliaSim:loadinfo]   mid1: 30943B4BBA1600002578
[CoppeliaSim:loadinfo]   mid2: 1B7B1C1E197E657D92856771AF57C050
[CoppeliaSim:loadinfo]   mid3: 46127579CA6F6C108415
```

**Comment by Coppelia** [comment]
2A8E13EFDBCEFD2A17AE4041
